-- Given the type declaration
--
-- data Expr = Val Int | Add Expr Expr
--
-- define a higher-order function
--
-- folde :: (Int -> a) -> (a -> a -> a) -> Expr -> a
--
-- such that folde f g replaces each Val constructor in an expression by the function f, and each Add constructor by the function g.
