-- Although not included in appendix B, the standard prelude defines
--
-- data Ordering = LT | EQ | GT
--
-- together with a function
--
-- compare :: Ord a => a -> a -> Ordering
--
-- that decides if one value in an ordered type is less than (LT), equal to (EQ), or greater than (GT) another value. Using this function, redefine the function occurs :: Ord a => a -> Tree a -> Bool for search trees. Why is this new definition more efficient than the original version?
