-- Implementing concatMap
-- The concat function joins a list of lists into a single list:
-- 
--   concat [[1,2,3],[4,5,6]]
--   [1,2,3,4,5,6]
-- 
-- Prelude provides a function named concatMap that can be naively implemented 
-- by composing concat and map:
-- 
--   concatMap f = concat . map f
-- 
-- Try implementing concatMap using foldl and foldr. Which one is better? Why?
