-- Given the type and instance declarations below, verify the functor laws for the Tree type, by induction on trees.
--
--   data Tree a = Leaf a | Node (Tree a) (Tree a)
--
--
--   instance Functor Tree where
--
--   -- fmap :: (a -> b) -> Tree a -> Tree b
--
--   fmap g (Leaf x)= Leaf (g x)
--
--   fmap g (Node l r) = Node (fmap g l) (fmap g r)
